kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: homer
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 8080
        protocol: TCP
      - containerPort: 31434
        hostPort: 31434
        protocol: TCP